# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69d876394f870c87ac0df34bee05afc4ed211599aa3e16ebfc5c6a9dfdcf204803b915dc87d65757f3db281e7120b66e1662794e7827367065675d98c43b9abf
  facebook_app_id: '1541902449471780'
  facebook_app_secret: 'd2c6c22543804491a5ca12608309fea0'
  github_app_id: 'f46f6ae6d89acc3ba649'
  github_app_secret: '0b0fc5149bf18f4734403f664b934bbd26206ba9'

test:
  secret_key_base: 4618b9df880af10b03884440679c6858106104793aeade9d88dcb2da20e59a3f47bc06c5621b478838d2e66e2e613b9753a69de9ad1cfce585f8258679a8df47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
